"""
Django settings for tienda_online project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from .config_product import PRODUCT_B   # Cambia PRODUCT_B → PRODUCT_A para la otra variante

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-*wu(*dfz!f@k8grh7qj74h%c(cd5rbx%-=1zb)n24*km18acie'
DEBUG = True
ALLOWED_HOSTS = []


# Application definition -----------------------------------------------------

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Proyecto
    'users',
    'inventario',
    'ventas',
    'reports',
    'notificaciones',
    'core',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tienda_online.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],  # Para plantillas personalizadas
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tienda_online.wsgi.application'


# Database -------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation ---------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization --------------------------------------------------------

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True


# Static files ---------------------------------------------------------------

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]


# Default primary key field type ---------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ----------------- CONFIGURACIÓN DE VARIABILIDAD (SPL) ----------------------

# De PRODUCT_A o PRODUCT_B del archivo config_product.py
from .config_product import PRODUCT_B   # Cambia a PRODUCT_A si deseas

ENABLE_REPORTS = PRODUCT_B["ENABLE_REPORTS"]
ENABLE_NOTIFICATIONS = PRODUCT_B["ENABLE_NOTIFICATIONS"]
